import { TextInput } from '@/components/atoms/CustomInput';
import { Box } from '@mui/material';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import { useRef } from 'react';
import { useForm } from 'react-hook-form';

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const { control, handleSubmit } = useForm({
    defaultValues: {
      name: '',
      address: '',
    },
  });
  const onSubmit = (data: any) => {
    console.log(data);
  };

  const onClickFocus = () => {
    inputRef.current?.focus();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header role="heading">welcome</header>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Box>
            <TextInput name="name" data-testid="name" control={control} ref={inputRef} />
          </Box>
          <Box>
            <TextInput name="address" data-testid="address" control={control} disabled={true} placeholder="asdfda" />
          </Box>
          <input type="submit" />
        </form>

        <button onClick={onClickFocus}>Focus on input</button>
      </main>
    </div>
  );
}
